baseURL = "https://lujia.netlify.app/"
languageCode = "en-us"
paginate = 6
theme = "portio-hugo"
title = "Lujia Huang"
  # Main Menu
  [[menu.main]]
    name = "Home"
    url = "#home"
    weight = 1
#  [[menu.main]]
#    name = "About"
#    url = "#about"
#    weight = 2
#  [[menu.main]]
#    name = "Service"
#    url = "#service"
#    weight = 3
#  [[menu.main]]
#    name = "Work"
#    url = "#portfolio"
#    weight = 4
  [[menu.main]]
    name = "Resume"
    url = "#resume"
    weight = 5
  [[menu.main]]
    name = "Blog"
    url = "#blog"
    weight = 6
  [[menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 7

  # Sitemap Menu
  [[menu.sitemap]]
    name = "About me"
    url = "#home"
    weight = 1
#  [[menu.sitemap]]
#    name = "Frequently Ask Question"
#    url = "#"
#    weight = 2
#  [[menu.sitemap]]
#    name = "Privacy & Policy"
#    url = "#"
#    weight = 3
  [[menu.sitemap]]
    name = "Latest Article"
    url = "blog"
    weight = 4

[params]
  blogPageURL = "blog"
  contactLink = "contact"
#  copyright = "All right reserved copyright © Portio 2020"
  footerLogo = "images/site-navigation/logo-white.png"
  formspreeURL = "YOUR FORMSPREE URL"
  googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
  logo = "images/site-navigation/logo-black.png"

  [params.address]
    address = "London Business School, Regent's Park, London, United Kingdom"
    email = "lhuang.mam2021@london.edu"
    openingHours = "10am to 6pm"
    phone = "+44 (0)20 7000 7000"

  [params.map]
    APIkey = "AIzaSyB2JuE_JhKjvzQsSxuV8p7XD-fq2uzLgGk"
    latitude = "51.526155"
    longitude = "-0.160668"
    pinImage = "images/pin.png"
